# FastAgent Configuration File

default_model: generic.qwen3:latest
execution_engine: "asyncio"

# Ollama
generic:
  api_key: "ollama"
  base_url: "http://localhost:11434/v1"

# Logging and Console Configuration:
logger:
    level: "info"
    type: "console"

    # Switch the progress display on or off
    progress_display: true

    # Show chat User/Assistant messages on the console
    show_chat: true
    # Show tool calls on the console
    show_tools: true
    # Truncate long tool responses on the console 
    truncate_tools: true

# MCP Servers
mcp:
    servers:
        aws-s3:
            command: "mcp"
            args: ["run", "main.py"]